version: '3'
services:
  app_servers_db:
    container_name: app_servers_db
    build: ./docker/db/
    ports:
      - "5452:5432"
    volumes:
      - app_servers_db:/var/lib/postgresql/data

volumes:
  app_servers_db:
    driver: local
